index:
  nothing: Nothing
  nothing_info: Oops! It looks like nothing was found at this location</br>Come back a little later
  404_info: Oops! It looks like nothing was found at this location.

about:
  hello: Hello

header:
  about: About
  archive: Archives
  search: Search
  tag: Tag

menu:
  about: About
  archive: Archives
  search: Search
  javascript: JavaScript
  hexo: Hexo
  swift: Swift
  utilities: Utilities

footer:
  wechat-follow: Follow Me on WeChat

page:
  more: Read More

post:
  share-wechat: Share to WeChat
  share-wechat-hint: Share to WeChat by scan Qrcode
  newer: Newer
  older: Older

algolia:
  input_placeholder: Seacrh Posts...
  hits_empty: No results for {{ query }}
