index:
  nothing: Nothing
  nothing_info: Oops! It looks like nothing was found at this location</br>Come back a little later
  404_info: Oops! It looks like nothing was found at this location.

about:
  hello: Hello

header:
  about: About
  archive: Archives
  search: Search
  tag: Tag

menu:
  about: About
  archive: Archives
  search: Search
  javascript: JavaScript
  css: CSS
  hexo: Hexo
  swift: Swift
  utilities: Utilities

footer:
  wechat-follow: Follow Me on WeChat

page:
  more: Read More

post:
  meta_posted: Posted on
  meta_cat: ' | in'
  share-wechat: Share to WeChat
  share-wechat-hint: Share to WeChat by scan Qrcode
  newer: Newer
  older: Older
  contents: Contents
  back_to_top: Back to Top
  is_helpful: Was this post helpful?
  updated: 'Last Updated: '

algolia:
  input_placeholder: Seacrh Posts...
  hits_empty: No results for {{ query }}
